### ISSUE TITLE
AMSTer Installation Errors: 

### ISSUE THREAD

**Issue by mirzawaqar** [AMSTerUsers/AMSTer_Distribution#4]
I did the installation of AMSTre distribution with the provided bash file. However, I am still facing state variables path missing in bashrc (although these paths are present in bashrc file). Similarly for 3rf party software and Specific system-based functions, I am getting directory missing warning. 

Testing components for AMSTer Software
--------------------------------------
--------------------------------------

1) STATE VARIABLES in bashrc or bash_profile
--------------------------------------------
--> PATHGNU:                                                passed	Value :	export PATHGNU=/usr/bin
export PATHGNU=$/usr/bin/gnuplot
export PATHGNU=/usr/bin
export PATHGNU=$/usr/bin/gnuplot
    PATHGNU not /usr/bin as expected for Linux. Please check
--> PATHFIJI:                                               passed	Value :	export PATHFIJI=$/home/contec/Softwares/Fiji.app/
export PATHFIJI=$/home/contec/Softwares/Fiji.app/
--> PATHCONV:                                               missing
--> PATHTOCPXFIDDLE:                                        passed	Value :	export PATHTOCPXFIDDLE=$/home/contec/Softwares/EXEC/
export PATHTOCPXFIDDLE=$/home/contec/Softwares/EXEC/
--> PATH_1650:                                              **missing**
--> PATH_3600:                                              **missing**
--> PATH_3601:                                              **missing**
--> PATH_3602:                                              **missing**
--> PATH_DataSAR:                                           **missing**
--> PATH_SCRIPTS:                                           **missing**
--> S1_ORBITS_DIR:                                          passed	Value :	export S1_ORBITS_DIR=${PATH_DataSAR}/SAR_AUX_FILES/ORBITS/S1_ORB
export S1_ORBITS_DIR=${PATH_DataSAR}/SAR_AUX_FILES/ORBITS/S1_ORB
--> ENVISAT_PRECISES_ORBITS_DIR:                            passed	Value :	export ENVISAT_PRECISES_ORBITS_DIR=${PATH_DataSAR}/SAR_AUX_FILES/ORBITS/ENV_ORB
export ENVISAT_PRECISES_ORBITS_DIR=${PATH_DataSAR}/SAR_AUX_FILES/ORBITS/ENV_ORB
--> EARTH_GRAVITATIONAL_MODELS_DIR:                         passed	Value :	export EARTH_GRAVITATIONAL_MODELS_DIR=${PATH_DataSAR}/SAR_AUX_FILES/EGM
export EARTH_GRAVITATIONAL_MODELS_DIR=${PATH_DataSAR}/SAR_AUX_FILES/EGM
--> EXTERNAL_DEMS_DIR:                                      passed	Value :	export EXTERNAL_DEMS_DIR=${PATH_DataSAR}/DEMS
export EXTERNAL_DEMS_DIR=${PATH_DataSAR}/DEMS
    EXTERNAL_DEMS_DIR is not mandatrory and actually not used with AMSTer Toolbox 

2) AMSTer Software main components
---------------------------------

Directories in $PATH in bashrc:
dirname: missing operand
Try 'dirname --help' for more information.
./Check_Installation.sh: line 459: $/usr/bin/gnuplot/grep: No such file or directory
--> AMSTerEngine in $PATH:                        failed       
dirname: missing operand
Try 'dirname --help' for more information.
./Check_Installation.sh: line 469: $/usr/bin/gnuplot/grep: No such file or directory
--> AMSTer Software SCRIPTS in $PATH:             failed       
./Check_Installation.sh: line 568: $/usr/bin/gnuplot/grep: No such file or directory
--> /SAR/EXEC in $PATH:                           failed       

Executables and versions:
--> AMSTerEngine                                  failed: missing at least initInSAR 
--> AMSTerEngine MSBAStools                       failed: missing at least getLineThroughStack 
dirname: missing operand
Try 'dirname --help' for more information.
--> AMSTer Software SCRIPTS                       failed: missing at least FUNCTIONS_FOR_MT.sh is in:  

3) Third party software
-----------------------
--> parallel:                                               passed	Version	GNU parallel 20161222 (in: /usr/bin)
--> gmt:                                                    passed	Version	6.0.0 (in: /usr/bin)
--> gnuplot:                                                passed	Version	gnuplot 5.4 patchlevel 1 (in: /usr/local/bin)
    Gnu version not in $PATHGNU? Please check!
--> bc  :                                                   passed	Version	bc 1.07.1 (in: /usr/bin)
--> convert:                                                passed	Version	Version: ImageMagick 6.9.10-23 Q16 x86_64 20190101 https://imagemagick.org (in: /usr/bin)
--> gdalinfo:                                               passed	Version	GDAL 3.6.2, released 2023/01/02 (in: /home/contec/Softwares/anaconda3/bin)
./Check_Installation.sh: line 226: $/usr/bin/gnuplot/grep: No such file or directory
--> snaphu:                                                 passed	Version	 (in: /usr/local/bin/snaphu)
./Check_Installation.sh: line 231: $/usr/bin/gnuplot/grep: No such file or directory
--> cpxfiddle:                                              passed	Version	 (in: /home/contec/SAR/EXEC/cpxfiddle)
--> wget:                                                   passed	Version	GNU Wget 1.20.3 built on linux-gnu. (in: /home/contec/Softwares/anaconda3/bin)
--> curl:                                                   passed	Version	curl 8.5.0 (x86_64-conda-linux-gnu) libcurl/8.5.0 OpenSSL/3.1.5 zlib/1.2.13 libssh2/1.10.0 nghttp2/1.57.0 (in: /home/contec/Softwares/anaconda3/bin)

    gsed	has more than one GNU version ? - pelase check: 
	/bin/gsed
	/usr/bin/gsed
     sed has more than one version: 
./Check_Installation.sh: line 164: $/usr/bin/gnuplot/gsed: No such file or directory
./Check_Installation.sh: line 165: $/usr/bin/gnuplot/gsed: No such file or directory
     sed:                                                   passed	Version	 sed  (in: /bin).  same as GNU version
./Check_Installation.sh: line 164: $/usr/bin/gnuplot/gsed: No such file or directory
./Check_Installation.sh: line 165: $/usr/bin/gnuplot/gsed: No such file or directory
     sed:                                                   passed	Version	 sed  (in: /usr/bin).  same as GNU version

    gawk	has more than one GNU version ? - pelase check: 
	/bin/gawk
	/usr/bin/gawk
     awk has more than one version: 
./Check_Installation.sh: line 164: $/usr/bin/gnuplot/gsed: No such file or directory
./Check_Installation.sh: line 165: $/usr/bin/gnuplot/gsed: No such file or directory
     awk:                                                   passed	Version	 awk  (in: /bin).  same as GNU version
./Check_Installation.sh: line 164: $/usr/bin/gnuplot/gsed: No such file or directory
./Check_Installation.sh: line 165: $/usr/bin/gnuplot/gsed: No such file or directory
     awk:                                                   passed	Version	 awk  (in: /usr/bin).  same as GNU version

    ggrep	has more than one GNU version ? - pelase check: 
	/bin/ggrep
	/usr/bin/ggrep
     grep has more than one version: 
./Check_Installation.sh: line 164: $/usr/bin/gnuplot/gsed: No such file or directory
./Check_Installation.sh: line 165: $/usr/bin/gnuplot/gsed: No such file or directory
     grep:                                                  passed	Version	 grep  (in: /bin).  same as GNU version
./Check_Installation.sh: line 164: $/usr/bin/gnuplot/gsed: No such file or directory
./Check_Installation.sh: line 165: $/usr/bin/gnuplot/gsed: No such file or directory
     grep:                                                  passed	Version	 grep  (in: /usr/bin).  same as GNU version

    gseq	has more than one GNU version ? - pelase check: 
	/bin/gseq
	/usr/bin/gseq
     seq has more than one version: 
./Check_Installation.sh: line 164: $/usr/bin/gnuplot/gsed: No such file or directory
./Check_Installation.sh: line 165: $/usr/bin/gnuplot/gsed: No such file or directory
     seq:                                                   passed	Version	 seq  (in: /bin).  same as GNU version
./Check_Installation.sh: line 164: $/usr/bin/gnuplot/gsed: No such file or directory
./Check_Installation.sh: line 165: $/usr/bin/gnuplot/gsed: No such file or directory
     seq:                                                   passed	Version	 seq  (in: /usr/bin).  same as GNU version

    gfind	has more than one GNU version ? - pelase check: 
	/bin/gfind
	/usr/bin/gfind
     find has more than one version: 
./Check_Installation.sh: line 164: $/usr/bin/gnuplot/gsed: No such file or directory
./Check_Installation.sh: line 165: $/usr/bin/gnuplot/gsed: No such file or directory
     find:                                                  passed	Version	 find  (in: /bin).  same as GNU version
./Check_Installation.sh: line 164: $/usr/bin/gnuplot/gsed: No such file or directory
./Check_Installation.sh: line 165: $/usr/bin/gnuplot/gsed: No such file or directory
     find:                                                  passed	Version	 find  (in: /usr/bin).  same as GNU version

    gstat	has more than one GNU version ? - pelase check: 
	/bin/gstat
	/usr/bin/gstat
     stat has more than one version: 
./Check_Installation.sh: line 164: $/usr/bin/gnuplot/gsed: No such file or directory
./Check_Installation.sh: line 165: $/usr/bin/gnuplot/gsed: No such file or directory
     stat:                                                  passed	Version	 stat  (in: /bin).  same as GNU version
./Check_Installation.sh: line 164: $/usr/bin/gnuplot/gsed: No such file or directory
./Check_Installation.sh: line 165: $/usr/bin/gnuplot/gsed: No such file or directory
     stat:                                                  passed	Version	 stat  (in: /usr/bin).  same as GNU version

    gdate	has more than one GNU version ? - pelase check: 
	/bin/gdate
	/usr/bin/gdate
     date has more than one version: 
./Check_Installation.sh: line 164: $/usr/bin/gnuplot/gsed: No such file or directory
./Check_Installation.sh: line 165: $/usr/bin/gnuplot/gsed: No such file or directory
     date:                                                  passed	Version	 date  (in: /bin).  same as GNU version
./Check_Installation.sh: line 164: $/usr/bin/gnuplot/gsed: No such file or directory
./Check_Installation.sh: line 165: $/usr/bin/gnuplot/gsed: No such file or directory
     date:                                                  passed	Version	 date  (in: /usr/bin).  same as GNU version

    guniq	has more than one GNU version ? - pelase check: 
	/bin/guniq
	/usr/bin/guniq
     uniq has more than one version: 
./Check_Installation.sh: line 164: $/usr/bin/gnuplot/gsed: No such file or directory
./Check_Installation.sh: line 165: $/usr/bin/gnuplot/gsed: No such file or directory
     uniq:                                                  passed	Version	 uniq  (in: /bin).  same as GNU version
./Check_Installation.sh: line 164: $/usr/bin/gnuplot/gsed: No such file or directory
./Check_Installation.sh: line 165: $/usr/bin/gnuplot/gsed: No such file or directory
     uniq:                                                  passed	Version	 uniq  (in: /usr/bin).  same as GNU version

    greadlink	has more than one GNU version ? - pelase check: 
	/bin/greadlink
	/usr/bin/greadlink
     readlink has more than one version: 
./Check_Installation.sh: line 164: $/usr/bin/gnuplot/gsed: No such file or directory
./Check_Installation.sh: line 165: $/usr/bin/gnuplot/gsed: No such file or directory
     readlink:                                              passed	Version	 readlink  (in: /bin).  same as GNU version
./Check_Installation.sh: line 164: $/usr/bin/gnuplot/gsed: No such file or directory
./Check_Installation.sh: line 165: $/usr/bin/gnuplot/gsed: No such file or directory
     readlink:                                              passed	Version	 readlink  (in: /usr/bin).  same as GNU version

    gxargs	has more than one GNU version ? - pelase check: 
	/bin/gxargs
	/usr/bin/gxargs
     xargs has more than one version: 
./Check_Installation.sh: line 164: $/usr/bin/gnuplot/gsed: No such file or directory
./Check_Installation.sh: line 165: $/usr/bin/gnuplot/gsed: No such file or directory
     xargs:                                                 passed	Version	 xargs  (in: /bin).  same as GNU version
./Check_Installation.sh: line 164: $/usr/bin/gnuplot/gsed: No such file or directory
./Check_Installation.sh: line 165: $/usr/bin/gnuplot/gsed: No such file or directory
     xargs:                                                 passed	Version	 xargs  (in: /usr/bin).  same as GNU version

    gdu	has more than one GNU version ? - pelase check: 
	/bin/gdu
	/usr/bin/gdu
     du has more than one version: 
./Check_Installation.sh: line 164: $/usr/bin/gnuplot/gsed: No such file or directory
./Check_Installation.sh: line 165: $/usr/bin/gnuplot/gsed: No such file or directory
     du:                                                    passed	Version	 du  (in: /bin).  same as GNU version
./Check_Installation.sh: line 164: $/usr/bin/gnuplot/gsed: No such file or directory
./Check_Installation.sh: line 165: $/usr/bin/gnuplot/gsed: No such file or directory
     du:                                                    passed	Version	 du  (in: /usr/bin).  same as GNU version

--> python:	passed		Need V3 for AMSTer. Python 3.11.6 found in /opt/local/bin
       Warning: a python exist in a default directory that is not the expected /opt/local/bin, i.e.:  
		/bin/python
		/home/contec/Softwares/anaconda3/bin/python
		/usr/bin/python
--> python3:	passed		Python 3.11.6 required for AMSTer found in /opt/local/bin
       Warning: a python3 exist in a default directory that is not the expected /opt/local/bin, i.e.:  
		/bin/python3
		/home/contec/Softwares/anaconda3/bin/python3
		/usr/bin/python3

--> Check modules for  /opt/local/bin/python 	
    numpy:	passed		Version	1.26.4 
    scipy:	passed		Version	1.11.4 
    matplotlib:	passed		Version	3.8.0 
    utm:	passed		Version	nr is missing though  
    osgeo:	passed		Version	3.6.2 (gdal)
    pip:	passed		Version	24.2 
    networkx:	passed		Version	3.1 
    PyQt6:	missing
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.35' not found (required by /home/contec/Softwares/anaconda3/lib/python3.11/site-packages/PyQt6/QtGui.abi3.so)
    opencv:	missing 

4) Specific system-based functions
----------------------------------
Testing libraries for MSBAS, AMSTerEngine etc...
./Check_Installation.sh: line 373: $/usr/bin/gnuplot/grep: No such file or directory
--> clang:                                                       failed       
./Check_Installation.sh: line 356: $/usr/bin/gnuplot/grep: No such file or directory
--> libfftw3-dev:                                                failed       
./Check_Installation.sh: line 356: $/usr/bin/gnuplot/grep: No such file or directory
--> libfftw3-long3:                                              failed       
./Check_Installation.sh: line 356: $/usr/bin/gnuplot/grep: No such file or directory
--> libfftw3-single3:                                            failed       
./Check_Installation.sh: line 356: $/usr/bin/gnuplot/grep: No such file or directory
--> libgeotiff-dev:                                              failed       
./Check_Installation.sh: line 356: $/usr/bin/gnuplot/grep: No such file or directory
--> libtiff-dev:                                                 failed       
./Check_Installation.sh: line 373: $/usr/bin/gnuplot/grep: No such file or directory
--> libxml2:                                                     failed       
./Check_Installation.sh: line 356: $/usr/bin/gnuplot/grep: No such file or directory
--> libxml2-dev:                                                 failed       
./Check_Installation.sh: line 356: $/usr/bin/gnuplot/grep: No such file or directory
--> liblapack-dev:                                               failed       
./Check_Installation.sh: line 356: $/usr/bin/gnuplot/grep: No such file or directory
--> libomp-dev:                                                  failed       
./Check_Installation.sh: line 356: $/usr/bin/gnuplot/grep: No such file or directory
--> libopenblas-dev:                                             failed       
./Check_Installation.sh: line 373: $/usr/bin/gnuplot/grep: No such file or directory
--> mpich:                                                       failed       
./Check_Installation.sh: line 799: $/usr/bin/gnuplot/grep: No such file or directory
./Check_Installation.sh: line 799: $/usr/bin/gnuplot/gawk: No such file or directory
--> ImageMagick :                                           	passed		Version	
./Check_Installation.sh: line 373: $/usr/bin/gnuplot/grep: No such file or directory
--> gdal:                                                        failed       
./Check_Installation.sh: line 356: $/usr/bin/gnuplot/grep: No such file or directory
--> libgdal-dev:                                                 failed       
./Check_Installation.sh: line 356: $/usr/bin/gnuplot/grep: No such file or directory
--> libhdf5-dev:                                                 failed       
./Check_Installation.sh: line 356: $/usr/bin/gnuplot/grep: No such file or directory
--> libnetcdf-dev:                                               failed       
./Check_Installation.sh: line 356: $/usr/bin/gnuplot/grep: No such file or directory
--> libgsl-dev:                                                  failed       
./Check_Installation.sh: line 373: $/usr/bin/gnuplot/grep: No such file or directory
--> gfortran:                                                    failed       
./Check_Installation.sh: line 818: $/usr/bin/gnuplot/grep: No such file or directory
./Check_Installation.sh: line 818: $/usr/bin/gnuplot/gawk: No such file or directory
--> g++:                                                    passed		Version	

Testing specific Linux features:
--> x-terminal-emulator:                                    passed	Version	 (in: /usr/bin/x-terminal-emulator)
--> espeak:                                                 passed	Version	 (in: /usr/bin/espeak)
--> OPENBLAS_NUM_THREADS=:                                  passed	Value :	export OPENBLAS_NUM_THREADS=1
export OPENBLAS_NUM_THREADS=1

5) Testing access to mandatory disk/directories:
------------------------------------------------
--> /SAR_AUX_FILES:                                                        **unreachable** ! 
--> /SAR_AUX_FILES/DEM:                                                    **unreachable** ! 
--> /SAR_AUX_FILES/ORBITS:                                                 **unreachable** ! 
--> /SAR_AUX_FILES/ORBITS/ENV_ORB:                                         **unreachable** ! 
--> /SAR_AUX_FILES/ORBITS/ENV_ORB/vor_gdr_d:                               **unreachable** ! 
--> /SAR_AUX_FILES/ORBITS/ERS:                                             **unreachable** ! 
--> /SAR_AUX_FILES/ORBITS/S1_ORB:                                          **unreachable** ! 
--> /SAR_AUX_FILES/ORBITS/S1_ORB/AUX_POEORB:                               **unreachable** ! 
--> /SAR_AUX_FILES/ORBITS/S1_ORB/AUX_RESORB:                               **unreachable** ! 
--> /SAR_AUX_FILES/Param_files:                                            **unreachable** ! 
--> /SAR_AUX_FILES/EGM/EGM96:                                              **unreachable** ! 

6) Testing some configs in mandatory files (Linux only):
--------------------------------------------------------
ImageMagick config file contains read & write rights for PS:	OK
ImageMagick config file contains read & write rights for EPS:	OK
ImageMagick config file contains height value up to 32KP:	OK
ImageMagick config file contains width value up to 32KP:	OK
ImageMagick config file contains disk value up to 8GiB:	OK

7) Testing usefull stuffs though not mandatory:
-----------------------------------------------
--> Gitkraken:                                              passed	Version	10.1.1
--> GIMP:                                                   passed	Version	GNU Image Manipulation Program version 2.10.38
--> JAVA:                                                   passed	Version	java.version = 11.0.24
--> ImageJ-Fiji  : failed, though it is not mnadatory
--> ImageJ-Fiji:                                  failed       
--> QGIS:                                                   passed	Version	QGIS 3.10.4-A Coruña 'A Coruña' (exported) 
    QGIS : You may want to install the following plugins (to do from within QGIS): 
  	- point sampling tool
  	- PointConnetor
  	- Profile tool
  	- Qdraw
  	- QuickMapServices
  	- RasterDataPlotting	(may require to install python first) 
  	- Serval
  	- Temporal/Spectal Profile Tool
  	- Value Tool

   //  As final notes: if you intend to run cron jobs, 
   //  	1) ensure that the following lines are commented in your .bashrc (if any) !! : 
				# If not running interactively, don't do anything
 					case hB in
						*i*) ;;
						*) return;;
					esac
   //  	2) ensure that the following state variable are exported at the beginning or the crontab !! : 
		export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/local/cuda/bin
		export LD_LIBRARY_PATH=:/usr/local/cuda/lib64
		export LD_INCLUDE_PATH=:/usr/local/cuda/include
		export LD_LIBRARY_PATH=:/usr/local/cuda/extras/CUPTI/lib64
		export PATH="/home/contec/Softwares/anaconda3/bin:$PATH"
		export PATH="/home/contec/Softwares/ISCE/isce2/contrib/stack/stripmapStack:$PATH"
		export PATH="/home/contec/Softwares/ISCE/isce2/contrib/stack/topsStack:$PATH"
		export PATH="/home/contec/Softwares/ISCE/isce2/contrib/stack/stripmapStack:$PATH"
		export PATH="/home/contec/Softwares/ISCE/isce2/contrib/stack/topsStack:$PATH"
		export PATH="/home/contec/Softwares/StaMPS/StaMPS_CONFIG.bash:$PATH"
		export PATH="home/contec/Softwares/TRAIN/APS_CONFIG.sh:$PATH"
		export GMTSAR=/home/contec/Softwares/GMTSAR
		export PATH=$GMTSAR/bin:"$PATH"
		export isbas=/home/contec/Softwares/isbas/
		export PATH=isbas:"$PATH"
		export PATHGNU=/usr/bin
		export JAVA_HOME=$/usr/lib/jvm/java-11-openjdk-amd64
		export PATHFIJI=$/home/contec/Softwares/Fiji.app/
		export PATHTOCPXFIDDLE=$/home/contec/Softwares/EXEC/
		export PATHGNU=$/usr/bin/gnuplot
		export OPENBLAS_NUM_THREADS=1
		export PATH_HOMEDATA=/media/hdd3/AMSTer/PATH_HOMEDATA
		export PATH_SynoData=/media/hdd3/AMSTer/PATH_SynoData
		export PATH_3610=/media/hdd3/AMSTer/PATH_1650
		export PATH_3610=/media/hdd3/AMSTer/PATH_3600
		export PATH_3610=/media/hdd3/AMSTer/PATH_3601
		export PATH_3610=/media/hdd3/AMSTer/PATH_3602
		export PATH_1660=/media/hdd3/AMSTer/PATH_1660
		export PATH_3610=/media/hdd3/AMSTer/PATH_DataSAR
		export PATH_3610=/media/hdd3/AMSTer/PATH_SCRIPTS
		export EXTERNAL_DEMS_DIR=${PATH_DataSAR}/DEMS
		export EARTH_GRAVITATIONAL_MODELS_DIR=${PATH_DataSAR}/SAR_AUX_FILES/EGM
		export ENVISAT_PRECISES_ORBITS_DIR=${PATH_DataSAR}/SAR_AUX_FILES/ORBITS/ENV_ORB
		export S1_ORBITS_DIR=${PATH_DataSAR}/SAR_AUX_FILES/ORBITS/S1_ORB
		export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/local/cuda/bin
		export LD_LIBRARY_PATH=:/usr/local/cuda/lib64
		export LD_INCLUDE_PATH=:/usr/local/cuda/include
		export LD_LIBRARY_PATH=:/usr/local/cuda/extras/CUPTI/lib64
		export PATH="/home/contec/Softwares/anaconda3/bin:$PATH"
		export PATH="/home/contec/Softwares/ISCE/isce2/contrib/stack/stripmapStack:$PATH"
		export PATH="/home/contec/Softwares/ISCE/isce2/contrib/stack/topsStack:$PATH"
		export PATH="/home/contec/Softwares/ISCE/isce2/contrib/stack/stripmapStack:$PATH"
		export PATH="/home/contec/Softwares/ISCE/isce2/contrib/stack/topsStack:$PATH"
		export PATH="/home/contec/Softwares/StaMPS/StaMPS_CONFIG.bash:$PATH"
		export PATH="home/contec/Softwares/TRAIN/APS_CONFIG.sh:$PATH"
		export GMTSAR=/home/contec/Softwares/GMTSAR
		export PATH=$GMTSAR/bin:"$PATH"
		export isbas=/home/contec/Softwares/isbas/
		export PATH=isbas:"$PATH"
		export PATHGNU=/usr/bin
		export JAVA_HOME=$/usr/lib/jvm/java-11-openjdk-amd64
		export PATHFIJI=$/home/contec/Softwares/Fiji.app/
		export PATHTOCPXFIDDLE=$/home/contec/Softwares/EXEC/
		export PATHGNU=$/usr/bin/gnuplot
		export OPENBLAS_NUM_THREADS=1
		export PATH_HOMEDATA=/media/hdd3/AMSTer/PATH_HOMEDATA
		export PATH_SynoData=/media/hdd3/AMSTer/PATH_SynoData
		export PATH_3610=/media/hdd3/AMSTer/PATH_1650
		export PATH_3610=/media/hdd3/AMSTer/PATH_3600
		export PATH_3610=/media/hdd3/AMSTer/PATH_3601
		export PATH_3610=/media/hdd3/AMSTer/PATH_3602
		export PATH_1660=/media/hdd3/AMSTer/PATH_1660
		export PATH_3610=/media/hdd3/AMSTer/PATH_DataSAR
		export PATH_3610=/media/hdd3/AMSTer/PATH_SCRIPTS
		export EXTERNAL_DEMS_DIR=${PATH_DataSAR}/DEMS
		export EARTH_GRAVITATIONAL_MODELS_DIR=${PATH_DataSAR}/SAR_AUX_FILES/EGM
		export ENVISAT_PRECISES_ORBITS_DIR=${PATH_DataSAR}/SAR_AUX_FILES/ORBITS/ENV_ORB
		export S1_ORBITS_DIR=${PATH_DataSAR}/SAR_AUX_FILES/ORBITS/S1_ORB

8) Check the .netrc file for accessing S1 orbits
------------------------------------------------
------------------------------------------------
 You already have a .netrc file in your home directroy  
 And it seems to have a line with login and password to dataspace.copernicus.eu 
	Nevertheless it the download of S1 orbits fails, double check your .netrc file contains a line as follow:
		machine identity.dataspace.copernicus.eu login <YourLogin> password <YourPassword>

9) Summary of all mounted hard disk (just for your info...):
------------------------------------------------------------
------------------------------------------------------------

Disks mounted by smb:
---------------------
df: smbfs: No such file or directory
df: smbfs: No such file or directory

Local disks:
------------
df: apfs: No such file or directory
df: apfs: No such file or directory

---------------------------------------------------------------------------------------------------

**Comment by ndoreye** [comment]
Hi Mirza, 

I guess you did your restart your computer after the installation as requested by the installer.  

Please check your .bashrc file. There must be some issues with the PATH definition and some variables: 

1. Ensure that the first path defined in your PATH state variable is /opt/local/bin (i.e. you should have somewhere "PATH=/opt/local/bin:$PATH")  

2. You seem to have more than one definition of PATHGNU variable. It must be (and only be) "export PATHGNU=/usr/bin" on Linux computer. From your message I can se that you also have export PATHGNU=$/usr/bin/gnuplot

3. The variable PATH_SCRIPTS is not defined. it must be something like ($HOME may be your home path instead)
"export PATH_SCRIPTS=$HOME/SAR/AMSTer"

4. The mandatory paths to the discs (or directories) where the different steps of the processing will be stored are missing. 
PATH_1650, PATH_3600, PATH_3601, PATH_3602 and PATH_DataSAR must be defined, eg. like 
export PATH_3602=/your_mounting_point/or_Path
export PATH_3601=/your_mounting_point/or_Path
export PATH_3600=/your_mounting_point/or_Path
export PATH_1650=/your_mounting_point/or_Path
export PATH_DataSAR=/your_mounting_point/or_Path
where "/your_mounting_point/or_Path" are either path to directories or externat discs 

5. as suggested during the installation, it is advised not to define EXTERNAL_DEMS_DIR. Remove the line  
"export EXTERNAL_DEMS_DIR=${PATH_DataSAR}/DEMS" from your bashrc.

As a conclusion, you bashrc should contains somathing like below. You can edit it and make changes accordingly, then reboot. 

Let me know if it helped. 

Nicolas 

 
PATH=/opt/local/bin:$PATH

# AMSTer VARIABLES
##################

export PATH_3602=/your_mounting_point/or_Path
export PATH_3601=/your_mounting_point/or_Path
export PATH_3600=/your_mounting_point/or_Path
export PATH_1650=/your_mounting_point/or_Path
export PATH_DataSAR=/your_mounting_point/or_Path
export EARTH_GRAVITATIONAL_MODELS_DIR=${PATH_DataSAR}/SAR_AUX_FILES/EGM
export ENVISAT_PRECISES_ORBITS_DIR=${PATH_DataSAR}/SAR_AUX_FILES/ORBITS/ENV_ORB
export S1_ORBITS_DIR=${PATH_DataSAR}/SAR_AUX_FILES/ORBITS/S1_ORB
export PATH_SCRIPTS=/$HOME/SAR/AMSTer
export PATHCONV=/usr/bin
export PATHFIJI=/$HOME/SAR/EXEC/Fiji.app/
export PATHGNU=/usr/bin
export PATHTOCPXFIDDLE=/$HOME/SAR/EXEC/
export PATH=$PATH 
export JAVA_HOME="/opt/local/Library/Java/JavaVirtualMachines/jdk-20-oracle-java-se.jdk/Contents/Home"

# AMSTer PATHS
##################

PATH=$PATH:/$HOME/SAR/EXEC
PATH=$PATH:/$HOME/SAR/AMSTer/MSBAS
PATH=$PATH:/$HOME/SAR/AMSTer/AMSTerEngine
PATH=$PATH:/$HOME/SAR/AMSTer/SCRIPTS_MT/_cron_scripts
PATH=$PATH:/$HOME/SAR/AMSTer/SCRIPTS_MT/AMSTerOrganizer
PATH=$PATH:/$HOME/SAR/AMSTer/SCRIPTS_MT/optimtoolbox
PATH=$PATH:/$HOME/SAR/AMSTer/SCRIPTS_MT/zz_Utilities_MT_Ndo
PATH=$PATH:/$HOME/SAR/AMSTer/SCRIPTS_MT/zz_Utilities_MT
PATH=$PATH:/$HOME/SAR/AMSTer/SCRIPTS_MT
